### ISSUE TITLE
Library doesn't work after recent .note file format change in beta

### ISSUE THREAD

**Issue by fbalobanov** [jya-dev/supernote-tool#10]
Ratta has changed the .note format in beta 2.04 (the latest beta is 2.05).

The library is failing to convert the note with "UnsupportedFileFormat: unsupported file" format exception.

Here is the link to the test note from the 2.05 beta: https://www.dropbox.com/s/neduuwiu4xiv14v/test.note?dl=0

**Comment by jya-dev** [comment]
Thank you for providing test note.

I added D.101 (beta 2.04) support and also added a parser policy feature.
commit: 3553976c55853fc1b229b3fbb58d0deeec4d31b8

Please check your other files created on beta 2.04 or 2.05.

The policy feature makes it easier for this library to continue to support future file format changes.
When you set `policy='loose'` parameter to `sn.load_notebook`, the parser try to parse unsupported file.
If you get next beta update and file format has changed, try this.
(Of course if the file format has changed significantly, the parser returns exception.)

``` python
notebook = sn.load_notebook(filename, policy='loose')
```

**Comment by fbalobanov** [comment]
So far it worked with a new format without policy=loose. I've checked on all my files\pages. Thanks!

**Comment by jya-dev** [comment]
Thanks for your confirmation.
I will close this issue after checking next stable firmware from Ratta.

**Comment by jya-dev** [comment]
Firmware update for X series has been released from Ratta finally!
I checked the new file format and needed some modifications.
The fix is done.
bffbc0451f20d330ca7261a103c392fa3235a879

**Comment by fbalobanov** [comment]
Thanks a lot for your fast updates!
