### ISSUE TITLE
Black background

### ISSUE THREAD

**Issue by enomis123** [jya-dev/supernote-tool#12]
Hi - I converted my .note file with a customised template (png) to pdf. The resulting file has a black background ( and not the template).  Is this a bug or do I have to change a specific setting ?  TIA.

**Comment by jya-dev** [comment]
Hi, thank you for your feedback.
It is probably a bug but I cannot reproduce the issue.
Could you share the template png file?

**Comment by enomis123** [comment]
Hi . Thank you for looking into the issue. PFA the template png that I used. 

![dots2](https://user-images.githubusercontent.com/52487947/147358601-611cd393-c590-472c-ba01-117559757ec1.png)

**Comment by jya-dev** [comment]
Your template file have _transparent_ background and many black dots.
If you use _white_ background and many black dots, you can avoid the black background issue.
I will update the tool to solve the issue for convenience.  Until the tool update, please use the workaround.

I attached modified png file.
![issue12_dots_custom_style_modified](https://user-images.githubusercontent.com/6436261/147360910-774ff45d-ab55-458f-b803-9ce36774703b.png)
