### ISSUE TITLE
Error on converting notes created on old firmware

### ISSUE THREAD

**Issue by jya-dev** [jya-dev/supernote-tool#13]
When I convert a note file with white background, conversion error occurs.
```
supernotelib.exceptions.DecoderException: uncompressed bitmap length = 42041344, expected = 2628288
```
The note file was created on C.368 (or maybe older) and updated to Chauvet 2.1.6.
New note files created on Chauvet 2.1.6 have no problem.

Tool version: v0.2.0
Input note file: created on C.368 and updated to Chauvet2.1.6

**Comment by steve8kv** [comment]
Looks like this issue has returned in Chauvet 3.22.31: 

  File "/opt/homebrew/lib/python3.11/site-packages/supernotelib/decoder.py", line 186, in decode
    raise exceptions.DecoderException(f'uncompressed bitmap length = {len(uncompressed)}, expected = {expected_length}')
supernotelib.exceptions.DecoderException: uncompressed bitmap length = 4915200, expected = 2628288
