### ISSUE TITLE
Support for the new fileformat for the latest beta

### ISSUE THREAD

**Issue by adityam** [jya-dev/supernote-tool#15]
Trying to convert a note file created on the latest beta gives an error:

```
exceptions.UnsupportedFileFormat('unsupported file format')
```
Is it possible to support the new file format.

**Comment by jya-dev** [comment]
Try `--policy loose` option.

Example:
```
supernote-tool convert --policy loose -a -t pdf your.note converted.pdf
```

I prepared the option for future file format changes.
When you give the option, the parser try to parse unsupported file.
If the beta file format is not big change from stable version, the option is helpful.
(Of course if the file format has changed significantly, the parser returns exception.)

I'm not in the Early Testers Program, so I can't support new file format soon.
If you could share your note file created by latest beta, I might be able to help you more.

**Comment by adityam** [comment]
Thanks. `--policy loose` does the conversion. The new beta version supports both internal and external links. A new version was released today. I'll create a sample file which includes all the features and post it here.

**Comment by adityam** [comment]
Here is a sample `.note` file and the corresponding `.pdf` as exported by the device.

[note file](https://www.dropbox.com/s/pjp1fvyfw2kdk0a/20221021_133518.note?dl=0)
[exported file](https://github.com/jya-dev/supernote-tool/files/9841604/20221021_133518.pdf)

**Comment by jya-dev** [comment]
Thank you for sharing sample files.
Chauvet 2.6.19 was now released while preparing beta support.
I have uploaded a support of Chauvet 2.6.19 at the latest commit (19583d484053bf57fede5d317a853729a2709156).
