### ISSUE TITLE
Publish on pypi.org for pip installs

### ISSUE THREAD

**Issue by jparris** [jya-dev/supernote-tool#17]
Hi there,

I think that publishing to pypi would simplify installs to `pip install supernote-tool`. 

Cheers, Jon

**Comment by jya-dev** [comment]
Thank you for your suggestion. I'm glad that there are more users than I originally thought. I've never registered on PyPI, so I'm trying to find out how to do it.

**Comment by geoffreycastillo** [comment]
Agree with @jparris. Right now this tool is the only one available to read notes directly. I think if it was slightly easier to install and had some kind of interface (for example using Gooey).

**Comment by jya-dev** [comment]
I have uploaded this tool to PyPI.
You can install with following command:
```
pip install supernotelib
```
