### ISSUE TITLE
Support new note files on Supernote A5X (and A6X?) Firmware (C.237)

### ISSUE THREAD

**Issue by iotku** [jya-dev/supernote-tool#2]
Although the tool worked on firmware C.203, after the new update today for my A5X (C.237) I receive a UnsupportedFileFormat exception when trying to convert notes that have been modified since the update.

Attached are an "-old" working .note file from firmware C.203 and a "-new" non-working .note file from after the upgrade. (.zip because github doesn't support .note)

[supernote notes A5X C.203 and C.237.zip](https://github.com/jya-dev/supernote-tool/files/5927696/supernote.notes.A5X.C.203.and.C.237.zip)

**Comment by jya-dev** [comment]
Thank you for providing A5X note file.
I found same issue on A6X (C.237) note file.

I'll analyze and try to fix it this weekend. Thanks.
