### ISSUE TITLE
pip install issue on venv - use pip3 --user parameter? on pip 65

### ISSUE THREAD

**Issue by bryantchambers** [jya-dev/supernote-tool#20]
Tried to follow ReadMe install but was met with: 

`ERROR: Could not install packages due to an OSError: Cannot move the non-empty directory`

[I found a suggested fix here](https://stackoverflow.com/questions/52949531/could-not-install-packages-due-to-an-environmenterror-errno-13)

This suggests running: 

`pip3 install package_name --user` with the fix of package_name = .

Proceeding, the scrips are then installed to the users local bin and must be added to the bash/zshell rc

are there any issues using this fix? is there a better way to proceed? sorry for baby terminal question here....

**Comment by jya-dev** [comment]
My recommendation is to use `venv` virtual environment as written in the README.
Within the virtual environment, you can install an application and dependent libraries without worrying about dependency version conflicts. The disadvantage is that the virtual environment must be activated before the application can be used.

The next recommended way is to use the `--user` option as you tried.
The software is installed locally by the user and does not affect the system. Note, however, that different versions of the same package cannot be installed at the same time. If the installation is successful, your method is fine.
