### ISSUE TITLE
feature: extract text from real-time recognition note?

### ISSUE THREAD

**Issue by andrewdownie** [jya-dev/supernote-tool#21]
Supernote just released real-time text conversion for notes, would it be possible to use this tool to extract the text?

**Comment by jya-dev** [comment]
I have added a new choice `txt` as conversion type on v0.4.0.
You can extract text from your real-time recognition note with following command:
```
supernote-tool convert -t txt -a your.note output.txt
```

**Comment by andrewdownie** [comment]
incredible, thank you!
