### ISSUE TITLE
Add page separator option into command line for text extraction

### ISSUE THREAD

**Issue by sokolgeo** [jya-dev/supernote-tool#44]
Hello!

I use supernote-tool to convert my .note file into .pdf and add an invisible text layer of recognized text into the pdt, making my notes searchable by standard tools.

This works fine, except I have to call supernote-tool in a loop to extract text from each page separately. Why? Because the all-page extracted text does not contain any marker separating one page from the other.

Practically could we have something like this:

`$ supernote-tool convert -t txt -a -page-separator="my unique page separator string" your.note output.txt`

This will add `my unique page separator string` as page separator, starting at the end of first page, allowing to call the `supernote-tool` once and use Linux `split`/`csplit` to further process the output.

Could this page separator functionality be implemented, please?

**Comment by jya-dev** [comment]
Good idea, I'll try to implement that functionality.

**Comment by jya-dev** [comment]
I added this feature and released it as v0.6.0.
https://github.com/jya-dev/supernote-tool/releases/tag/v0.6.0
